# [K] (c)@2020

name: r2s-19 07 4

on:
  push:
    branches: 
      - master
    paths: 
      - 'JUNK/r2s_original2_base.conf'
      - 'JUNK/r2s_original2_user.conf'
      - 'JUNK/r2s_original2_user_little.conf'
      - '.github/workflows/r2s_original2-19.07.4.yml'
      - 'patch_dosth.sh'
      - 'scripts/original-package.sh'
      - 'scripts/copy*.sh'
      - 'scripts/patch_for_r2s.sh'
      - 'version'

jobs:

  build:
    
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y install bc build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          git config --global user.name "kongfl888"
          git config --global user.email "kongfl888@outlook.com"
          
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/kongfl888/friendlywrt_manifests -b master-v19.07.4 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8

      - name: Patch For R2S
        run: |
          . ./scripts/patch_for_r2s.sh

      - name: Patch For kernel 5.4
        run: |
          . ./scripts/patch_for_r2s_5.4.sh 0

      - name: Mods
        run: |
          cd friendlywrt-rk3328
          #. ../remove_unused_config.sh
          . ../patch_dosth.sh
          #sed -i 's/CONFIG_BPFILTER=y/CONFIG_BPFILTER=n/' kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
          sed -i 's/dnsmasq /dnsmasq-full /' friendlywrt/include/target.mk
          [ -f configs/config_rk3328 ] && sed -i '/adblock/d;/docker/d;/DOCKER/d;/mwan3/d;/OPENVPN/d;/openvpn/d;' configs/config_rk3328
          cat ../JUNK/r2s_original2_base.conf >> configs/config_rk3328
          cat ../JUNK/r2s_original2_kmod.conf >> configs/config_rk3328
          cat ../JUNK/r2s_original2_user_little.conf >> configs/config_rk3328
          cat ../JUNK/r2s_original2_user.conf >> configs/config_rk3328
          cd friendlywrt
          mv ../../scripts/one_time_init.sh package/base-files/files/usr/bin && sed -i '/exit/i\/bin/sh /usr/bin/one_time_init.sh 13 &' package/base-files/files/etc/rc.local
          mv ../../scripts/flash_rom.sh package/base-files/files/root/flash_rom.sh && chmod +x package/base-files/files/root/flash_rom.sh
          . ../../scripts/add-for-statusview.sh
          . ../../scripts/buildtime.sh
          rm -f ./feeds.conf.default && wget -O ./feeds.conf.default https://raw.githubusercontent.com/openwrt/openwrt/v19.07.4/feeds.conf.default

      - name: Clean Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds clean -a

      - name: Add Luci-theme
        run: |
          . ./scripts/add-theme-argon.sh 1

      - name: Add Luci-i18n-sqm-zh-cn
        run: |
          git clone -b master --single-branch https://github.com/kongfl888/luci-i18n-sqm-zh-cn.git
          mv luci-i18n-sqm-zh-cn friendlywrt-rk3328/friendlywrt/package

      - name: Add Luci-app-timedreboot
        run: |
          git clone -b master --single-branch https://github.com/kongfl888/luci-app-timedreboot.git
          mv luci-app-timedreboot friendlywrt-rk3328/friendlywrt/package

      - name: Add Luci-app-r2sflasher
        run: |
          git clone -b master --single-branch https://github.com/kongfl888/luci-app-r2sflasher.git
          mv luci-app-r2sflasher friendlywrt-rk3328/friendlywrt/package

      - name: Add Luci-app-autorewan
        run: |
          git clone -b master --single-branch https://github.com/kongfl888/luci-app-autorewan.git
          mv luci-app-autorewan friendlywrt-rk3328/friendlywrt/package

      - name: Add check-network
        run: |
          git clone -b master --single-branch https://github.com/kongfl888/check-network.git
          mv check-network friendlywrt-rk3328/friendlywrt/package

      - name: Add AdGuardHome
        run: |
          git clone -b master --single-branch https://github.com/kongfl888/luci-app-adguardhome.git
          mv luci-app-adguardhome friendlywrt-rk3328/friendlywrt/package
          mkdir -p friendlywrt-rk3328/friendlywrt/package/adguardhome && cd friendlywrt-rk3328/friendlywrt/package/adguardhome
          wget https://raw.githubusercontent.com/Lienol/openwrt/dev-19.07/package/diy/adguardhome/Makefile

      - name: Add luci-app-koolproxyR
        run: |
          git clone -b master --single-branch https://github.com/project-openwrt/luci-app-koolproxyR
          cd luci-app-koolproxyR
          git apply ../patches/make-koolproxyR-default-to-arm.patch
          cd ..
          mv luci-app-koolproxyR friendlywrt-rk3328/friendlywrt/package

      - name: Add IPTV Helper
        run: |
          git clone -b master --single-branch https://github.com/riverscn/openwrt-iptvhelper.git
          mv openwrt-iptvhelper/iptvhelper friendlywrt-rk3328/friendlywrt/package
          mv openwrt-iptvhelper/luci-app-iptvhelper friendlywrt-rk3328/friendlywrt/package
          sed -i 's/+luci-compat //' friendlywrt-rk3328/friendlywrt/package/luci-app-iptvhelper/Makefile
          sed -i 's/+luci-compat//g' friendlywrt-rk3328/friendlywrt/package/luci-app-iptvhelper/Makefile

      - name: Add SSR
        run: |
          git clone -b master --single-branch https://github.com/fw876/helloworld.git
          mv helloworld/luci-app-ssr-plus/po/zh-cn  helloworld/luci-app-ssr-plus/po/zh_Hans || echo ""
          mv -f helloworld/luci-app-ssr-plus friendlywrt-rk3328/friendlywrt/package

      - name: Add Passwall
        run: |
          cd friendlywrt-rk3328/friendlywrt
          echo -e '\nsrc-git lienol https://github.com/Lienol/openwrt-package' >> feeds.conf.default
          ./scripts/feeds update -a
          rm -rf feeds/lienol/lienol/ipt2socks
          rm -rf feeds/lienol/lienol/shadowsocksr-libev
          rm -rf feeds/lienol/lienol/pdnsd-alt
          rm -rf feeds/lienol/package/verysync
          rm -rf feeds/lienol/lienol/luci-app-verysync
          rm -rf package/lean/luci-app-kodexplorer
          rm -rf package/lean/luci-app-pppoe-relay
          rm -rf package/lean/luci-app-pptp-server
          rm -rf package/lean/luci-app-v2ray-server
          ./scripts/feeds install -a

      - name: Update Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Update package
        run: |
          git clone -b openwrt-19.07 --single-branch https://github.com/project-openwrt/openwrt.git
          . ./scripts/original-package.sh 13

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          . ../scripts/rename_sdimg.sh 13 || echo ""
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img
      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./r2srom/
          mkdir -p ./r2srom/
          mkdir -p ./r2sconfig/
          mkdir -p ./imgs/
          . ./scripts/ls-dir.sh friendlywrt-rk3328 > ./r2sconfig/workdir.txt
          mv friendlywrt-rk3328/out/*img* ./r2srom/
          cd ./r2srom/
          sha256sum *img* > sha256sum.txt
          cd ..
          mkdir -p ./ipks/
          . ./scripts/copyipk.sh
          cd ./ipks/
          sha256sum *ipk > packages.sha256
          cd ..
          cp ./README.txt ./r2srom/
          cp ./scripts/checksha256.sh ./r2srom/
          . ./scripts/copyimg.sh
          . ./scripts/copyconfig.sh
          zip -r artifact.zip ./r2srom/
          zip -r ipks.zip ./ipks/
          zip -r imgs.zip ./imgs/
          zip -r r2sconfig.zip ./r2sconfig/
          release_tag="R2S-Original-19.07.4-$(date +%Y-%m-%d-%H)"
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
      - name: Upload Release Asset Ipk
        id: upload-release-asset-ipk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./ipks.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ipk.zip
          asset_content_type: application/zip
      - name: Upload Release Asset Config
        id: upload-release-asset-config
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./r2sconfig.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-config.zip
          asset_content_type: application/zip
      - name: Upload Release Asset Img
        id: upload-release-asset-img
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./imgs.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-imgs.zip
          asset_content_type: application/zip
# end
